title = "Gitleaks Configuration"

[allowlist]
description = "Global Allowlist"
paths = [
    '''node_modules''',
    '''dist''',
    '''package-lock.json''',
    '''yarn.lock''',
    '''go.sum''',
    '''.gitleaks.toml''',
    '''tests/'''
]
regexes = [
    '''edge-functions-key''',
    '''sb_secret_(?:REDACTED|\.{3})''',
    '''Deno\.env\.get''',
    '''local-secret-key''',
    '''local-access-key''',
    '''postgresql:\/\/postgres:<password>@db\.<project>\.supabase\.co''',
    '''postgresql:\/\/postgres:\*\*\*@db\.xxx\.supabase\.co''',
    '''postgresql:\/\/postgres:\$\{[A-Z0-9_]+\}@\$\{[A-Z0-9_]+\}''',
    '''postgres:\/\/postgres\.your-tenant-id:your-super-secret-and-long-postgres-password@localhost'''
]

# Common password and key patterns
[[rules]]
id = "generic-api-key"
description = "Detect Generic API Keys"
regex = '''(?i)(?:^|[\s,{])(?:[A-Z0-9_]*?(?:openai(?:_|-)?api(?:_|-)?key|supabase(?:_|-)?anon(?:_|-)?key|service(?:_|-)?role(?:_|-)?key|service(?:_|-)?api(?:_|-)?key|anon(?:_|-)?key|api(?:_|-)?key|access(?:_|-)?key(?:_|-)?(?:id|secret)?|secret(?:_|-)?key(?:_|-)?base|secret(?:_|-)?key|jwt(?:_|-)?secret|auth(?:_|-)?token|refresh(?:_|-)?token|id(?:_|-)?token|bearer(?:_|-)?token|private(?:_|-)?access(?:_|-)?token|public(?:_|-)?access(?:_|-)?token|password|passwd|pwd|smtp(?:_|-)?pass(?:word)?|vault(?:_|-)?enc(?:_|-)?key)[A-Z0-9_]*)\s*[:=]\s*(?:['"][A-Za-z0-9._~!$%+=:@\/-]{8,}['"]|[A-Za-z0-9._~!$%+=:@\/-]{8,})'''
tags = ["key", "API", "generic"]
severity = "HIGH"

[[rules]]
id = "aws-access-key"
description = "AWS Access Key"
regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
tags = ["key", "AWS"]
severity = "HIGH"

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Key"
regex = '''(?i)aws(.{0,20})?(?-i)['\"][0-9a-zA-Z\/+]{40}['\"]'''
tags = ["key", "AWS"]
severity = "HIGH"

[[rules]]
id = "github-pat"
description = "GitHub Personal Access Token"
regex = '''ghp_[0-9a-zA-Z]{36}'''
tags = ["key", "GitHub"]
severity = "HIGH"

[[rules]]
id = "private-key"
description = "Private Key File"
regex = '''-----BEGIN ((EC|PGP|DSA|RSA|OPENSSH) )?PRIVATE KEY( BLOCK)?-----'''
tags = ["key", "private"]
severity = "CRITICAL"

[[rules]]
id = "google-api-key"
description = "Google API Key"
regex = '''AIza[0-9A-Za-z\\-_]{35}'''
tags = ["key", "Google"]
severity = "HIGH"

[[rules]]
id = "slack-webhook"
description = "Slack Webhook"
regex = '''https://hooks.slack.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24}'''
tags = ["key", "Slack"]
severity = "HIGH"

[[rules]]
id = "basic-auth"
description = "Basic Authentication Header"
regex = '''(?i)(?:(?:authorization|proxy-authorization)\s*:\s*)?basic\s+[A-Za-z0-9+\/]{16,}={0,2}'''
tags = ["auth", "credentials"]
severity = "HIGH"

[[rules]]
id = "password-in-url"
description = "Password in URL"
regex = '''[a-zA-Z]{3,10}:\/\/[^\/\s:@]+:[^\/\s:@]{4,}@[^\/\s:@]+'''
tags = ["auth", "credentials"]
severity = "HIGH"
