name: Build/release

# If the commit is tagged with a version (e.g. "v1.0.0"),
# release the app
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: macos-latest-large
            arch: x64
          - os: macos-latest
            arch: arm64
          - os: ubuntu-latest
            arch: x64
          - os: windows-latest
            arch: x64

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Build/release Electron app
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build
          npx tsc --project tsconfig.electron.json
          npx electron-builder --config electron-builder.json --publish onTag --${{ matrix.arch }} -c.publish.provider=github -c.publish.releaseType=draft
